### ISSUE TITLE
Running Migrations

### ISSUE THREAD

**Issue by matthewhall-ca** [colopl/laravel-spanner#3]
Hey @colopl-workplace team! Are you guys currently using migrations within Laravel at all? or just manually doing your schemas in Cloud Spanner?

We would like to propose adding a custom `spanner:migrate` command to the package that would override the default migrate system to work with Cloud Spanner.

If you're open to this we'll start development and open a PR when it's complete!

**Comment by castaneai** [comment]
Hi, @matthewhall-ca,
We appreciate your contribution.

We are not using migration within Laravel.
Instead we recreate the entire database with [`extra_statements[]` parameter](https://cloud.google.com/spanner/docs/reference/rpc/google.spanner.admin.database.v1#createdatabaserequest) because running Cloud Spanner's DDL individually is very slow.

>adding a custom spanner:migrate command

That would be great!

**Comment by matthewhall-ca** [comment]
Ahhh that does make sense, we did notice that the migrations run VERY slowly when done manually.

We'll start working on it soon and PR when it's done!  Thanks so much for open sourcing this project guys!

**Comment by matthewjumpsoffbuildings** [comment]
@MatthewHallCom any updates on this?

@castaneai I feel like the lack of proper migrations really cramps the standard laravel style or doing things, I know in the docs you say there is no AUTO INCREMENT but surely that cant be enough of a reason to completely ignore any migration ability?

**Comment by MatthewHallCom** [comment]
We decided not to continue with Cloud Spanner. We have since implemented Google Cloud's AlloyDB for PostgreSQL

**Comment by matthewjumpsoffbuildings** [comment]
From a quick investigation it looks like AlloyDB doesnt have the same level of horizontal scalability as Spanner?

**Comment by MatthewHallCom** [comment]
Correct, its definitely not as horizontally scalable, but was good enough for our needs

**Comment by taka-oyama** [comment]
So Spanner recently implemented something similar to auto increment called [sequence generator](https://cloud.google.com/solutions/sequence-generation-in-cloud-spanner). I will try to use it to implement `Blueprint::increments` once they have the feature is implemented into [spanner emulator](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator) (which I need for testing).

**Comment by matthewjumpsoffbuildings** [comment]
This doesnt look like a solution? According to that document this is not a Spanner-implemented solution, rather
> This document proposes mechanisms for implementing a sequence generator by using a Spanner database table and application layer logic.

Also as the document notes, we dont want to create monotonically incrementing values since that will create hotspotting and fundamentally defeat the shardability and scalability of the database

What is really needed is something like Datastore has for its keys - https://cloud.google.com/appengine/docs/legacy/standard/go111/datastore/creating-entity-keys#Assigning_identifiers:
> You can configure Datastore to generate auto IDs... The default policy generates a random sequence of unused IDs that are approximately uniformly distributed. Each ID can be up to 16 decimal digits long.

**Comment by matthewjumpsoffbuildings** [comment]
Upon further research it exists. https://cloud.google.com/spanner/docs/primary-key-default-value
```sql
CREATE TABLE Fans (
  FanId varchar(36) DEFAULT spanner.generate_uuid(),
  Name text,
  PRIMARY KEY (FanId)
);
```
or
```sql
CREATE SEQUENCE SingerIdSequence bit_reversed_positive;

CREATE TABLE Singers (
  SingerId bigint DEFAULT nextval('SingerIdSequence'),
  Name text,
  PRIMARY KEY (SingerId)
);
```

What should really be happening, since monotonically increasing values is an anti-pattern, is that any time a migration uses `increments()` is it gets mapped to one of either the spanner `GENERATE_UUID` function or a bit reversed value, though i think the UUID is maybe the preferred pattern?

**Comment by taka-oyama** [comment]
I plan on going with bit reversed sequence because it uses INT64 which is aligned with other databases.

**Comment by matthewjumpsoffbuildings** [comment]
That makes sense, I guess its a good middle ground between keeping a similar data type and avoiding such a strong anti-pattern
